
package proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BankServices", targetNamespace = "http://ws.enset/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BankServices {


    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod(operationName = "Convert")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Convert", targetNamespace = "http://ws.enset/", className = "proxy.Convert")
    @ResponseWrapper(localName = "ConvertResponse", targetNamespace = "http://ws.enset/", className = "proxy.ConvertResponse")
    @Action(input = "http://ws.enset/BankServices/ConvertRequest", output = "http://ws.enset/BankServices/ConvertResponse")
    public double convert(
        @WebParam(name = "Montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @return
     *     returns java.util.List<proxy.Compte>
     */
    @WebMethod(operationName = "ListComptes")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ListComptes", targetNamespace = "http://ws.enset/", className = "proxy.ListComptes")
    @ResponseWrapper(localName = "ListComptesResponse", targetNamespace = "http://ws.enset/", className = "proxy.ListComptesResponse")
    @Action(input = "http://ws.enset/BankServices/ListComptesRequest", output = "http://ws.enset/BankServices/ListComptesResponse")
    public List<Compte> listComptes();

    /**
     * 
     * @param code
     * @return
     *     returns proxy.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://ws.enset/", className = "proxy.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://ws.enset/", className = "proxy.GetCompteResponse")
    @Action(input = "http://ws.enset/BankServices/getCompteRequest", output = "http://ws.enset/BankServices/getCompteResponse")
    public Compte getCompte(
        @WebParam(name = "Code", targetNamespace = "")
        int code);

}
