
package proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "BanqueEnset", targetNamespace = "http://ws.enset/", wsdlLocation = "http://localhost:5000/?wsdl")
public class BanqueEnset
    extends Service
{

    private static final URL BANQUEENSET_WSDL_LOCATION;
    private static final WebServiceException BANQUEENSET_EXCEPTION;
    private static final QName BANQUEENSET_QNAME = new QName("http://ws.enset/", "BanqueEnset");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:5000/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BANQUEENSET_WSDL_LOCATION = url;
        BANQUEENSET_EXCEPTION = e;
    }

    public BanqueEnset() {
        super(__getWsdlLocation(), BANQUEENSET_QNAME);
    }

    public BanqueEnset(WebServiceFeature... features) {
        super(__getWsdlLocation(), BANQUEENSET_QNAME, features);
    }

    public BanqueEnset(URL wsdlLocation) {
        super(wsdlLocation, BANQUEENSET_QNAME);
    }

    public BanqueEnset(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BANQUEENSET_QNAME, features);
    }

    public BanqueEnset(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BanqueEnset(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BankServices
     */
    @WebEndpoint(name = "BankServicesPort")
    public BankServices getBankServicesPort() {
        return super.getPort(new QName("http://ws.enset/", "BankServicesPort"), BankServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BankServices
     */
    @WebEndpoint(name = "BankServicesPort")
    public BankServices getBankServicesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.enset/", "BankServicesPort"), BankServices.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BANQUEENSET_EXCEPTION!= null) {
            throw BANQUEENSET_EXCEPTION;
        }
        return BANQUEENSET_WSDL_LOCATION;
    }

}
